brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todos/', include("todos.urls")),
    path('admin/', admin.site.urls),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListListView
)







urlpatterns = [
    path("todo/", TodoListListView.as_view(), name="todo_list")
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey("TodoList", related_name="items", on_delete = models.CASCADE)

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView

from todos.models import TodoList, TodoItem
# Create your views here.


class TodoListListView(ListView):
    model = TodoList
    tempelate_name = "todos/list.html"

class TodoItemListView(ListView):
    model = TodoItem
    tempelate_name = "todos/list.html"

todos/templates/todos/create.html
<!doctype html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        
    </body>
</html>

todos/templates/todos/delete.html
<!doctype html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        
    </body>
</html>

todos/templates/todos/detail.html
<!doctype html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        
    </body>
</html>

todos/templates/todos/edit.html
<!doctype html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        
    </body>
</html>

todos/templates/todos/list.html
<!doctype html>
<html>
    <head>
        <title>Todo Lists</title>
    </head>
    <body>
        <main>
          {% for name in todolist_list %}
            <div>
                <h2>
                    <a href="{% url 'todo_list_detail' todolist.pk %}">{{ todolist.name }}</a>
                </h2>
            </div>
          {% endfor %}
        </main>
    </body>
</html>